### ISSUE TITLE
Problem with library file name?

### ISSUE THREAD

**Issue by theirishpenguin** [saygoweb/ansible-plugin-copyv#3]
On your Ansible 2.x branch should the library file be called copyv rather than copyv.py?

**Comment by cambell-prince** [comment]
I don't think so.

**Comment by theirishpenguin** [comment]
Oh, okay. When it was called copyv.py ansible couldn't find the task. And when I renamed it to copyv then it did find it (though I got another error). I renamed the file as I had noticed that under the section "A Solution Tying Them Together" in this article...

http://ndemengel.github.io/2015/01/20/ansible-modules-and-action-plugins/

... it refers to the module "./library/backup" (no extension).

Feel free to close this bug if you think it is invalid.
